version: '3'
services:
  node1:
    build: .
    restart: always
    ports:
      - "127.0.0.1:3001:3001"
      - "6001:6001"
    environment:
      - HTTP_PORT=3001
      - P2P_PORT=6001
      - PEERS=
      - PRIVATE_KEY=node/wallet/private_key_1
    volumes:
      - ./node/wallet:/app/node/wallet

  node2:
    build: .
    restart: always
    ports:
      - "127.0.0.1:3002:3002"
      - "6002:6002"
    environment:
      - HTTP_PORT=3002
      - P2P_PORT=6002
      - PEERS=ws://node1:6001
      - PRIVATE_KEY=node/wallet/private_key_2
    volumes:
      - ./node/wallet:/app/node/wallet
    depends_on:
      - node1
