version: '3'
services:
  node:
    build: .
    container_name: quantix-node
    restart: always
    ports:
      - "3001:3001"
      - "6001:6001"
    environment:
      - HTTP_PORT=3001
      - P2P_PORT=6001
      - PEERS=
      - PRIVATE_KEY=node/wallet/private_key
      - ENABLE_MINING=true
    deploy:
      resources:
        limits:
          memory: 600M
          # memory-swap: 2G # Only works if swap is enabled on host
    volumes:
      - ./genesis_key.json:/app/node/wallet/private_key
      - ./node/data:/app/data
      # Also mount the whole wallet dir just in case, but specific key mapping is safer or use a .env
